{
    "openapi": "3.0.0",
    "info": {
        "title": "ISMO API Documentation",
        "description": "Ismo Api documentation description",
        "contact": {
            "email": "contact@nxb.com.pk"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://127.0.0.1:8000/api/v1",
            "description": "API Base URL"
        }
    ],
    "paths": {
        "/jobs": {
            "get": {
                "tags": [
                    "Jobs & Job Applications"
                ],
                "summary": "Get list of Published Jobs",
                "description": "Returns list of Jobs",
                "operationId": "getPublishedJobs",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/job/{slug}": {
            "get": {
                "tags": [
                    "Jobs & Job Applications"
                ],
                "summary": "Get Specific Job against slug",
                "description": "Returns list of Jobs",
                "operationId": "showSingleJob",
                "parameters": [
                    {
                        "name": "slug",
                        "in": "path",
                        "description": "Job slug",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/submit-job-application": {
            "post": {
                "tags": [
                    "Jobs & Job Applications"
                ],
                "summary": "Submit Job Application",
                "description": "Submit Job Application in the resource",
                "operationId": "submitApplication",
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "gender",
                                    "city",
                                    "experience",
                                    "phone",
                                    "degree_level",
                                    "degree_title",
                                    "address",
                                    "job_slug",
                                    "resume"
                                ],
                                "properties": {
                                    "name": {
                                        "title": "Name",
                                        "type": "string"
                                    },
                                    "email": {
                                        "title": "email",
                                        "type": "string"
                                    },
                                    "gender": {
                                        "title": "gender",
                                        "type": "string"
                                    },
                                    "phone": {
                                        "title": "phone",
                                        "type": "string"
                                    },
                                    "experience": {
                                        "title": "experience",
                                        "type": "string"
                                    },
                                    "city": {
                                        "title": "city",
                                        "type": "string"
                                    },
                                    "degree_level": {
                                        "title": "degree_level",
                                        "type": "string"
                                    },
                                    "degree_title": {
                                        "title": "degree_title",
                                        "type": "string"
                                    },
                                    "address": {
                                        "title": "address",
                                        "type": "string"
                                    },
                                    "job_slug": {
                                        "title": "job_slug",
                                        "type": "string"
                                    },
                                    "resume": {
                                        "title": "resume",
                                        "type": "file"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "John Doe",
                                    "email": "johndoe@email.com",
                                    "gender": "male",
                                    "experience": "2 Years",
                                    "phone": "03001234567",
                                    "degree_level": "Masters",
                                    "degree_title": "MSC",
                                    "address": "USA",
                                    "city": "California"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/save-chat-initiator-details": {
            "post": {
                "tags": [
                    "Chatbot Queries"
                ],
                "summary": "save chat initiator details",
                "description": "save chat initiator details in the resource",
                "operationId": "store",
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "phone",
                                    "send_chat_history"
                                ],
                                "properties": {
                                    "name": {
                                        "title": "Name",
                                        "type": "string"
                                    },
                                    "email": {
                                        "title": "email",
                                        "type": "string"
                                    },
                                    "phone": {
                                        "title": "phone",
                                        "type": "string"
                                    },
                                    "company": {
                                        "title": "company",
                                        "type": "string"
                                    },
                                    "send_chat_history": {
                                        "title": "send_chat_history",
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "John Doe",
                                    "email": "johndoe@email.com",
                                    "phone": "03001234567",
                                    "send_chat_history": "0"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/chatbot-query": {
            "post": {
                "tags": [
                    "Chatbot Queries"
                ],
                "summary": "Submit asked query and matches it",
                "description": "Submit asked query and matches it in the resource",
                "operationId": "askQuestion",
                "parameters": [
                    {
                        "name": "x-initiator-key",
                        "in": "header",
                        "description": "Chat initiator unique token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "question"
                                ],
                                "properties": {
                                    "question": {
                                        "title": "question",
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "question": "Is this a question?"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/close-chat": {
            "get": {
                "tags": [
                    "Chatbot Queries"
                ],
                "summary": "Initimate Client and admin about the chat history",
                "description": "Initimate Client and admin about the chat history by sending emails to them.",
                "operationId": "sendChatHistoryEmail",
                "parameters": [
                    {
                        "name": "x-initiator-key",
                        "in": "header",
                        "description": "Chat initiator unique token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/upload-attachments": {
            "post": {
                "tags": [
                    "Clients"
                ],
                "summary": "Upload Client's Document",
                "description": "Upload document in the resource",
                "operationId": "store",
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "phrase",
                                    "attachment"
                                ],
                                "properties": {
                                    "category": {
                                        "title": "category",
                                        "type": "string"
                                    },
                                    "phrase": {
                                        "title": "phrase",
                                        "type": "string"
                                    },
                                    "attachment": {
                                        "title": "attachment",
                                        "type": "file"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/remove-attachments": {
            "post": {
                "tags": [
                    "Clients"
                ],
                "summary": "Remove Client's Document",
                "description": "Remove document in the resource",
                "operationId": "destroy",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "category",
                                    "phrase"
                                ],
                                "properties": {
                                    "category": {
                                        "title": "category",
                                        "type": "string"
                                    },
                                    "phrase": {
                                        "title": "phrase",
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "category": "2",
                                    "phrase": "test"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/auth/register": {
            "post": {
                "tags": [
                    "Clients"
                ],
                "summary": "Register Client",
                "description": "This API will register the client in the resource and will return a token, This token will be used to proceed next API calls for succesfull client registration.",
                "operationId": "register",
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "name",
                                    "address",
                                    "type",
                                    "categories",
                                    "pri_name",
                                    "pri_email",
                                    "pri_address",
                                    "pri_telephone",
                                    "pri_facsimile_telephone",
                                    "sec_name",
                                    "sec_email",
                                    "sec_address",
                                    "sec_telephone",
                                    "sec_facsimile_telephone",
                                    "pri_signature",
                                    "sec_signature"
                                ],
                                "properties": {
                                    "name": {
                                        "title": "Name",
                                        "type": "string"
                                    },
                                    "address": {
                                        "title": "Address",
                                        "type": "string"
                                    },
                                    "type": {
                                        "title": "Type",
                                        "type": "string"
                                    },
                                    "categories": {
                                        "title": "Categories",
                                        "type": "string"
                                    },
                                    "pri_name": {
                                        "title": "Primary Name",
                                        "type": "string"
                                    },
                                    "pri_email": {
                                        "title": "Primary Email",
                                        "type": "string"
                                    },
                                    "pri_address": {
                                        "title": "Primary Address",
                                        "type": "string"
                                    },
                                    "pri_telephone": {
                                        "title": "Primary Telephone",
                                        "type": "string"
                                    },
                                    "pri_facsimile_telephone": {
                                        "title": "Primary Facsimile Telephone",
                                        "type": "string"
                                    },
                                    "sec_name": {
                                        "title": "Secondary Name",
                                        "type": "string"
                                    },
                                    "sec_email": {
                                        "title": "Secondary Email",
                                        "type": "string"
                                    },
                                    "sec_address": {
                                        "title": "Secondary Address",
                                        "type": "string"
                                    },
                                    "sec_telephone": {
                                        "title": "Secondary Telephone",
                                        "type": "string"
                                    },
                                    "sec_facsimile_telephone": {
                                        "title": "Secondary Facsimile Telephone",
                                        "type": "string"
                                    },
                                    "pri_signature": {
                                        "title": "Primary Signature",
                                        "type": "file"
                                    },
                                    "sec_signature": {
                                        "title": "Secondary Signature",
                                        "type": "file"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "John Doe",
                                    "address": "USA",
                                    "type": "service_provider",
                                    "categories": "2,3,4",
                                    "pri_name": "John",
                                    "pri_email": "johndoe@gmail.com",
                                    "pri_address": "USA, California",
                                    "pri_telephone": "03001234567",
                                    "pri_facsimile_telephone": "03001234567",
                                    "sec_name": "Doe",
                                    "sec_email": "johndoe@gmail.com",
                                    "sec_address": "USA, California",
                                    "sec_telephone": "03001234567",
                                    "sec_facsimile_telephone": "03001234567"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/submit-query": {
            "post": {
                "tags": [
                    "Contact Us"
                ],
                "summary": "Submit Constact Form Query",
                "description": "Submit Constact Form Query in the resource",
                "operationId": "store",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "subject",
                                    "message"
                                ],
                                "properties": {
                                    "name": {
                                        "title": "name",
                                        "type": "string"
                                    },
                                    "email": {
                                        "title": "email",
                                        "type": "string"
                                    },
                                    "subject": {
                                        "title": "subject",
                                        "type": "string"
                                    },
                                    "message": {
                                        "title": "message",
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "John Doe",
                                    "email": "johndoe@email.com",
                                    "subject": "Query Subject",
                                    "message": "Query Message"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/documents": {
            "get": {
                "tags": [
                    "Documents"
                ],
                "summary": "Get list of Published Documents",
                "description": "Returns list of Documents",
                "operationId": "getPublishedDocs",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/search-document?key=": {
            "post": {
                "tags": [
                    "Documents"
                ],
                "summary": "Search Document from the resource",
                "description": "Search Document from the resource",
                "operationId": "search",
                "parameters": [
                    {
                        "name": "key",
                        "in": "query",
                        "description": "Search Key",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/faqs": {
            "get": {
                "tags": [
                    "Faqs"
                ],
                "summary": "Get list of Published faqs",
                "description": "Returns list of faqs",
                "operationId": "show",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/media-libraries": {
            "get": {
                "tags": [
                    "Media Library"
                ],
                "summary": "Get list of Media Libraries with featured image",
                "description": "Returns Media Libraries with featured image",
                "operationId": "mediaLibraryList",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/media-libraries/{slug}": {
            "get": {
                "tags": [
                    "Media Library"
                ],
                "summary": "Get list of Media Library files",
                "description": "Returns Media Library files",
                "operationId": "mediaFiles",
                "parameters": [
                    {
                        "name": "slug",
                        "in": "path",
                        "description": "Media Library slug",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/menus": {
            "get": {
                "tags": [
                    "Menus"
                ],
                "summary": "Get list of Menus by active theme",
                "description": "Returns Menus by active theme",
                "operationId": "getMenus",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/subscribe-to-newsletter": {
            "post": {
                "tags": [
                    "Newsletters"
                ],
                "summary": "Subscribe Newsletter",
                "description": "Subscribe to Newsletters",
                "operationId": "subscribe",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "email"
                                ],
                                "properties": {
                                    "email": {
                                        "title": "email",
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "johndoe@email.com"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/pages/{slug}": {
            "get": {
                "tags": [
                    "Pages"
                ],
                "summary": "Get Specific Page against slug",
                "description": "Returns single Page",
                "operationId": "show",
                "parameters": [
                    {
                        "name": "slug",
                        "in": "path",
                        "description": "Page slug",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/news-and-blogs": {
            "get": {
                "tags": [
                    "Posts"
                ],
                "summary": "Get list of Published Posts",
                "description": "Returns list of Posts",
                "operationId": "getPublishedPosts",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/announcements": {
            "get": {
                "tags": [
                    "Posts"
                ],
                "summary": "Get list of Published Announcements",
                "description": "Returns list of Announcements",
                "operationId": "getPublishedAnnouncements",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/post-menu": {
            "get": {
                "tags": [
                    "Posts"
                ],
                "summary": "Get post categories menu list",
                "description": "Get post categories menu list",
                "operationId": "postMenus",
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/posts/{category}": {
            "get": {
                "tags": [
                    "Posts"
                ],
                "summary": "Get post categories menu list",
                "description": "Get post categories menu list",
                "operationId": "getPostsByCategory",
                "parameters": [
                    {
                        "name": "category",
                        "in": "path",
                        "description": "Post category listed in post menu",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/posts/{category}/{slug}": {
            "get": {
                "tags": [
                    "Posts"
                ],
                "summary": "Get Specific Post against slug",
                "description": "Returns single Post",
                "operationId": "getSinglePost",
                "parameters": [
                    {
                        "name": "category",
                        "in": "path",
                        "description": "Post category",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "slug",
                        "in": "path",
                        "description": "Post slug",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "402": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Site Search"
                ],
                "summary": "Search records from the whole site. (FAQs, Jobs, Documents, Posts, Pages)",
                "description": "This search API will work for FAQs, Posts, Jobs and Pages when 'type' property is not set or 'type' property is set to 'web_content'. If the 'type' property is set to 'document' then the API will only search from the Documents Module",
                "operationId": "siteSearch",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "key"
                                ],
                                "properties": {
                                    "key": {
                                        "title": "key",
                                        "type": "string"
                                    },
                                    "type": {
                                        "title": "type",
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "key": "John Doe",
                                    "type": ""
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/sitemap": {
            "get": {
                "tags": [
                    "Sitemap"
                ],
                "summary": "Get list of Published Pages",
                "description": "Returns list of Pages",
                "operationId": "index",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/slider-images": {
            "get": {
                "tags": [
                    "Slider Images"
                ],
                "summary": "Get list of Slider Images",
                "description": "Returns Slider Images",
                "operationId": "getSliderImages",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        },
        "/static-blocks": {
            "get": {
                "tags": [
                    "Static Blocks"
                ],
                "summary": "Get list of Static Blocks",
                "description": "Returns Static Blocks",
                "operationId": "show",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Could not found"
                    }
                },
                "security": [
                    {
                        "BearerAppKey": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "BearerAppKey": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"
            },
            "BearerToken": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"
            }
        }
    },
    "security": [
        []
    ]
}